exports.ChargerModel=
{
    Handshek: { type:String},
    Host: { type:String},
    HttpVersion:{ type:String },
    LastActiveTime:{ type:String},
    LocationEndPoint: { type:String},
    Method :{type:String },
    Origin: { type:String},
    ChargerId :{type:String},
    RemoteEndPoint:{type:String},
    SecWebSocketProtocol:{ type:String},
    SecWebSocketVersion: { type:String},
    SessionId :{ type:String },
    ChargerConnection :{ type:String },
    Last_ActiveTime :{ type:String },
    LastDown_Time :{ type:String },
    UpDown_Time :{ type:String },
    StartTime :{ type:String },
    Upgrade  :{ type:String },
    db_chid  :{ type:String },
    cpoid :{ type:String },
    cponame  :{ type:String },
    stationid  :{ type:String },
    stationname  :{ type:String },
    clientid :{ type:String },
    clientname  :{ type:String },
    MessageTypeNo :{ type:String },
    MessageId :{ type:String },
    MessageCode  :{ type:String },
    Action :{ type:String },
    idTag  :{ type:String },
    ParentidTag  :{ type:String },
    reservationId  :{ type:String },
    expirydate :{ type:String },
    Status :{ type:String },
    Heartbeat :{ type:String },
    Heartbeat1  :{ type:String },
    Action1  :{ type:String },
    blank :{ type:String },
    HeartbeatId :{ type:String },
    StartTransaction :{ type:String },
    ConnectorId  :{ type:String },
    RequestMessage  :{ type:String },
    metervalue_timestamp  :{ type:String },
    metervalue_sampledvalue_value  :{ type:String },
    metervalue_sampledvalue_context :{ type:String },
    metervalue_sampledvalue_format  :{ type:String },
    metervalue_sampledvalue_measurandEnergy :{ type:String },
    metervalue_sampledvalue_measurandCurrent  :{ type:String },
    measurandEnergyLocation :{ type:String },
     measurandCurrentLocation  :{ type:String },
    metervalue_sampledvalue_location  :{ type:String },
     metervalue_sampledvalue_unit  :{ type:String },
    TransactionId :{ type:String },
     meterstop :{ type:String },
    meterstart  :{ type:String },
    reason :{ type:String },
    errorCode  :{ type:String },
    errorMessage :{ type:String },
    info  :{ type:String },
    status  :{ type:String },
    Timestamp  :{ type:String },
    StartTranMsgId  :{ type:String },
    StartTransactionId  :{ type:String },
    idTagInfo :{ type:String },
    RemoteTestClient :{ type:String },
    OrignalVal  :{ type:String },
    ChargerPointModel  :{ type:String },
     ChargerPointSerialNo :{ type:String },
     ChargerPointVendor :{ type:String },
    FirmwareVersion :{ type:String },
    StopTransaction :{ type:String },
    StopTranMsgId :{ type:String },
    StopTransactionId :{ type:String },
    StopsReason :{ type:String },
    RemoteStop :{ type:String },
    RemoteMsgId  :{ type:String },
    RemoteMsgCode :{ type:String },
    RemoteTransactionId :{ type:String },
    RemoteCommand:{ type:String },
    RequestFrom:{ type:String },
    CSerialNo :{ type:String },
    Chargerid:{ type:String },
    ModelList:{ type:Array },
}

exports.Model_List=
{
    Charger_id:{ type:String },
    status :{ type:String },
    SerialNo :{ type:String },
    model_id :{ type:String },
    ModelName:{ type:String },
    Charger_Type :{ type:String },
    InterVal :{ type:String },
    value:{ type:String },
    context:{ type:String },
    format :{ type:String },
    measurand:{ type:String },
    location :{ type:String },
    phase :{ type:String },
    unit:{ type:String },
    transactionid:{ type:String },
    connectorid :{ type:String },
    chargerid :{ type:String },
    idTag:{ type:String },
    MessageId:{ type:String },
    MessageCode:{ type:String },
    EventName :{ type:String },
    metertimestamp:{ type:String },
    meterstart:{ type:String },
    meterstop:{ type:String },
    timestamp:{ type:String },
    reason:{ type:String },
    db_chid:{ type:String },
    cpoid:{ type:String },
    cponame:{ type:String },
    stationid:{ type:String },
    stationname:{ type:String },
    clientid:{ type:String },
    clientname:{ type:String },
    charger_srno :{ type:String },
    is_dualgun:{ type:String },
    otp :{ type:String },
    ErrMsg:{ type:String },
    expiry_date:{ type:String },
    customTransId:{ type:String },
    Detail:{ type:Array }
}
